### PR TITLE
good stuff

### PR DESCRIPTION
**Pull request by Confuseh**
WEBKIT BROWSER = FIXES EVERYTHING LITERALLY EVERYTHING YET KEEPS LOW CPU RAM USAGE
STUFF STARTED TO WORK ON YET NOT IMPLEMENTED:
- FFZ CHANNEL EMOTES
- EMOTE MENU - LITERALLY DOESNT DO SHIT
- BIT MORE EXPANSION ON MENTION DOESNT DO MUCH SHIT EITHER
- FIXED LINK REGEX
- MAYBE SOMETHING ELSE I FORGOT

I TYPE IN ALL CAPS BECAUSE IM HAVING AN HEART ATTACK BRB

### CODE REVIEW

**Comment by gempir** [comment]
Electron didn't die for this...

**Comment by pajlada** [comment]
@gempir The performance is actually good though, unlike Electron :sunglasses::ok_hand:

**Comment by gempir** [comment]
If you write shitty code it's bound to be slow, Electron is just a bit more punishing in that.

**Comment by Confuseh** [comment]
seems good

**Pull request merged**
